services:
  ws:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: nats-jetstream-example
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      nats-server:
        condition: service_started
    environment:
      - nats.url=nats://nats-server:4222
      - nats.username=nats
      - nats.password=secret

  nats-server:
    image: nats:2.10
    container_name: nats-server
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    command:
      - "-js"
      - "-m"
      - "8222"
      - "--store_dir=/data/jetstream"
      - "--user=nats"
      - "--pass=secret"
    volumes:
      - nats_data:/data/jetstream

volumes:
  nats_data: